### ISSUE TITLE
Library is not available on the maven repository - Demo is not compiling

### ISSUE THREAD

**Issue by AndreasBoehm** [fingerprintjs/fingerprintjs-pro-android-demo#23]
I tried to run the Demo because i could not get the latest version working in my project but the demo is not compiling because the library is not available.

Error
```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.fingerprint.android:pro:2.1.0.
```

Could you please take a look?

Thanks

**Comment by Alexey-Verkhovsky** [comment]
Hey! Sorry for the long response. We've met some troubles with the distribution mechanism, but now it's under control. Please try again – now it should work correctly.

**Comment by AndreasBoehm** [comment]
Thanks @Alexey-Verkhovsky! Everything is working fine now.

**Comment by anshulkhattar** [comment]
How did you make it work? I'm still getting the same error. @AndreasBoehm @Alexey-Verkhovsky

**Comment by AndreasBoehm** [comment]
Hi @anshulkhattar, I think that @Alexey-Verkhovsky fixed something on the maven repository. I did not had to change anything on my side.

**Comment by anshulkhattar** [comment]
> Hi @anshulkhattar, I think that @Alexey-Verkhovsky fixed something on the maven repository. I did not have to change anything on my side.

Hey @Alexey-Verkhovsky can you please look into this?

**Comment by Alexey-Verkhovsky** [comment]
Hello @anshulkhattar. Our maven repository works as expected without issues. Perhaps you've met a different problem. Make sure you've added our repository to your `settings.gradle` file. Follow the instructions from [this section](https://github.com/fingerprintjs/fingerprintjs-pro-android-demo#quick-start).

**Comment by anshulkhattar** [comment]
> Hello @anshulkhattar. Our maven repository works as expected without issues. Perhaps you've met a different problem. Make sure you've added our repository to your `settings.gradle` file. Follow the instructions from [this section](https://github.com/fingerprintjs/fingerprintjs-pro-android-demo#quick-start).

Hey @Alexey-Verkhovsky , I did follow the steps to setup , but getting this error

> Unable to resolve dependency for ':app@devDebug/compileClasspath': Could not resolve com.fingerprint.android:pro:2.1.0.

**Comment by Alexey-Verkhovsky** [comment]
Could you please provide content of `settings.gradle` and `build.gradle` files (without NDA content, obviously)? 
On our end everything works as expected.
