### ISSUE TITLE
Changelog for version 2.1.1 missing

### ISSUE THREAD

**Issue by AndreasBoehm** [fingerprintjs/fingerprintjs-pro-android-demo#24]
My renovate bot is suggesting an update to version 2.1.1 of the fingerprintjs pro library but i can't find a changelog for that version.

**Comment by Alexey-Verkhovsky** [comment]
@AndreasBoehm thanks for the heads up!
You may get familiar with the changelog [here](https://github.com/fingerprintjs/fingerprintjs-pro-android-demo/releases/tag/v2.1.1)

**Comment by AndreasBoehm** [comment]
Thanks a lot
