### ISSUE TITLE
Duplicated class with another external SDK

### ISSUE THREAD

**Issue by zuhriyansauqi** [fingerprintjs/fingerprintjs-pro-android-demo#26]
Hi, I got an issue when integrating FingerprintJSPro SDK.
It throwing a RuntimeException which says "Duplicate class a.a, a.b, and a.c found in jetifier modules (another SDK) and jetifier module (FJSPro SDK)."

Do I need another configuration step?

**Comment by Alexey-Verkhovsky** [comment]
@zuhriyansauqi is the another SDK name public, can you reveal it to us? It could be helpful. If it's under NDA – then no more questions.

**Comment by Alexey-Verkhovsky** [comment]
Hello, we're released the updated version (2.2.0), there you should not meet the same problem. Note, that the 2.2.0 requires an additional dependency (our OSS library – [FingerprintJS-Android](https://github.com/fingerprintjs/fingerprintjs-android))
