### ISSUE TITLE
Class import failed.

### ISSUE THREAD

**Issue by vikashprajapati** [fingerprintjs/fingerprintjs-pro-android-demo#38]
Any class present in 
**import com.fingerprintjs.android.fpjs_pro**
not detected in the sample project.
Failed to resolve: com.fingerprint.android:pro:2.3.0

**Comment by Alexey-Verkhovsky** [comment]
Hey! 
Have you added [our maven repository](https://github.com/fingerprintjs/fingerprintjs-pro-android-demo#add-the-repository-to-the-gradle) in the module `build.gradle` file?

**Comment by Alexey-Verkhovsky** [comment]
I close the issue since there is no contact from the other side. Please, reopen it if the advice doesn't work for you.
